### ISSUE TITLE
GLIBC_2.32 missing

### ISSUE THREAD

**Issue by dariotarantini** [curlpipe/ox#109]
**Describe the bug**
Cant run, it says: 
`ox: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ox)`

 - OS: KDE neon User Edition 5.21 x86_64

**Comment by gut5** [comment]
same problem here

**Comment by p32929** [comment]
me too. OS: Ubuntu 20.04

**Comment by acz2022** [comment]
yep, same here OS: Ubuntu 21.10

**Comment by curlpipe** [comment]
I think this happens when the pre-compiled binary from the releases page is used on certain systems
I use a rolling-release distro and thus have compiled it with a newer version of libc6

A fix for this would be to try and build from source (which shouldn't take too long on most systems, probably around a maximum of about 1-2 minutes).

The command for this is `cargo install --git https://github.com/curlpipe/ox`

Closing for now, I don't have an ubuntu system that would have a lower version of libc6
