### ISSUE TITLE
Some questions regarding this project?

### ISSUE THREAD

**Issue by Raj2032** [curlpipe/ox#121]
Hi guys I have some questions regarding this project:
1. Is this project still alive?
2. Is it like dwm where you would modify part of the source code as the source code is the settings?

**Comment by curlpipe** [comment]
1. Unfortunately not, I'm having real trouble trying to get unicode, syntax highlighting and file buffering to work together, I've been trying for a long time, but it's not working.
2. See https://github.com/curlpipe/ox#configuring-ox for more information on configuration.

**Comment by Raj2032** [comment]
Hi @curlpipe 

1. Would this still be an issue if it was written in another language due to how Rust can be restrictive?
2. Thanks for the link :)

**Comment by Raj2032** [comment]
@curlpipe I see mate, its a shame the project couldn't continue. I would have loved to help but I don;t know much about this stuff. Hope to see it opened up soon :)

**Comment by adsick** [comment]
I'm interested in this project too, it looks nice to me. Previously I've watched at Helix and neovim, but Helix is too obsessed with their "kakoune" style editing which is bad and vim/neovim is a scripting hell when it comes to setting it up as an ide. It also is too hard to learn but not because it's modal, it is because it lacks discoverability I guess - hundreds of keybinds in different mods which are pretty hard to access with :help command.

**Comment by adsick** [comment]
btw if you think that supporting unicode is too hard (which I don't really believe tbh) then I'd simply drop it as you can perfectly live without it.

**Comment by curlpipe** [comment]
New release recently, I've managed to solve my issues with unicode and syntax highlighting, and lua can be used to configure the editor

I'm thinking of implementing editor commands in lua to allow plugins to be written, but this is a work in progress (and shouldn't be too difficult)
