### ISSUE TITLE
question: any orientation in what is possible with custom commands?

### ISSUE THREAD

**Issue by kurokirasama** [curlpipe/ox#130]
can i call shell functions?

**Comment by curlpipe** [comment]
Custom commands can be defined in your configuration file, which you will need to create in `~/.oxrc` for (assuming you are on Linux or Mac) you can find more info on the config file [here in the wiki](https://github.com/curlpipe/ox/wiki/Configuration)

I'm working on updating the documentation at the moment to include the new API for writing plugins, for now, there is a default configuration file found in the `config/.oxrc` file, which shows an example of how to add custom commands and assign key bindings

You can run shell commands with any plug-ins you write, as the configuration language is Lua and therefore you have access to everything included with that language as standard.

For reference, the way to run a shell command is using the following code:

```lua
handle = io.popen(command)
result = handle:read("*a")
handle:close()
```

which stores the output of the command in the `result` variable

Once the documentation is updated, I'll let you know (so you know how you can use the output and play around with the editor itself i.e. showing messages or writing text)

**Comment by curlpipe** [comment]
I have updated this page of the documentation with a new plug-in section, which explains how to write plugins and run them once you're in the editor, this can be found [here](https://github.com/curlpipe/ox/wiki/Configuration#plug-ins)

Feel free to let me know if you have any further questions.

**Comment by kurokirasama** [comment]
hey again, is there any way to get the number of lines of the current file?

**Comment by kurokirasama** [comment]
trying to learn here:

this command works:
```lua
["clear"] = function(number_of_lines)
        editor:move_top() 
        for i = 1, number_of_lines[1] do
            editor:remove_line()
        end
    
        editor:display_info("File content cleared")
    end
```

but If I try to set a keybind:
```lua
 ["ctrl_l"] = function()
        editor:move_top() 
        for i = 1, 30 do
            editor:remove_line()
        end
    
        editor:display_info("File content cleared")
    end,
```
ox closes and got this error:
```
panicked at /home/kira/.cargo/registry/src/index.crates.io-6f17d22bba15001f/synoptic-2.0.3/src/lib.rs:379:20:
removal index (is 0) should be < len (is 0)
Aborted (core dumped)
```

**Comment by curlpipe** [comment]
Hi, there is currently no easy way to obtain the number of lines in the document. However, I'm about to add this into 0.4.2 which will likely be released today - along with updated documentation (as I've expanded the API).

I will let you know when this update is released and give an example of how to query the number of lines in the document.

As for the plugins you've written. I copied your plug-in into my config and they both seem to work (but removing 3 lines instead of 30), I think this error is because you might be pressing ctrl+l on a file that is less than 30 lines in length. Let me know if this isn't the case.

Either way, it shouldn't panic and instead display an error letting you know that the index is out of bounds.

**Comment by curlpipe** [comment]
0.4.2 has been pushed, which should fix the errors you are encountering above

See the configuration section (linked above) to see the expanded editor API

As promised, for finding the number of lines in a document, you can use the following: `editor.document_length`
