### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by curlpipe** [curlpipe/ox#19]
**Is your feature request related to a problem? Please describe.**
Syntax highlighting for Ox. 

**Describe the solution you'd like**
Should be done by having regex in a configuration file and have Ox read those regular expressions and highlighting it with the specified colour. Should also come with languages like Rust, JavaScript, Python and Ruby and C too.

**Describe alternatives you've considered**
~~Being a total chad and not using any syntax highlighting~~

**Comment by curlpipe** [comment]
Making solid progress on Syntax highlighting, now managed to implement basic syntax highlighting with Rust, plan to add in multiline comment support and fix a few bugs here and there.

![image](https://user-images.githubusercontent.com/11898833/94746925-59edb000-036d-11eb-96aa-7551e961d584.png)

**Comment by curlpipe** [comment]
Whoops accidentality closed, such an amateur move!

**Comment by curlpipe** [comment]
![image](https://user-images.githubusercontent.com/11898833/94843754-adfba180-040c-11eb-9d16-e7e16c4b4e0d.png)
I've since fixed issues with overflowing text, they now hold their colours when being trimmed down

**Comment by curlpipe** [comment]
Now working on multiline highlight support (e.g. multiline comments)

**Comment by sidju** [comment]
Good job on setting up your own implementation. I was considering doing the same for a while.
I am using syntect for the initial highlighting in my editor and custom logic for printing, [relevant code here](https://github.com/sidju/hired/blob/master/src/ui/print.rs).

(You may note that the conversion into crossterm colors is a bit odd. That is because I use a hack to represent ANSI 16-color with the lower bytes of the R if the alpha value is 0 (transparent), as advised by syntects developer. All in all this allows me to support Sublime's syntax and theme definitions, which is pretty neat but has yet to be exploited by me.)

**Comment by curlpipe** [comment]
@sidju Haha you've discovered me talking to myself. I never intended for this to blow up :laughing:. I looked at syntect but I wasn't comfortable with adding a ton of dependencies to my project as syntect is pretty heavy. I'm currently setting up a different implementation that will render multiline comments properly as the current implementation is a bit buggy here and there. It's going well and hopefully it'll be finished by the end of the week. It's great to see that I'm not the only Rust text editor developer around, i'll be sure to check out your text editor, it looks fantastic!

**Comment by curlpipe** [comment]
Added in syntax highlighting in latest update, however, it is inefficient in some cases, especially when dealing with a lot of multiline tokens in files. I plan to fix this in a few updates time, for now, I plan to work on adding more crucial features to Ox including multitasking and macros and after that I'll vastly improve efficiency.
