### ISSUE TITLE
Paste multi-line

### ISSUE THREAD

**Issue by pboling** [curlpipe/ox#191]
**What is the bug?**

Unable to paste text that has new lines.

**What did you do to get the bug?**

Copy text with new lines... such as this random example:
```
➕ rubocop-capybara, rubocop-factory_bot

Error: The `RSpec/Capybara/FeatureMethods` cop has been removed since this cop has migrated to `RSpec/Dialect`. Please use `RSpec/Dialect` instead.
(obsolete configuration found in config/default.yml, please update it)
`RSpec/Capybara/*` has been extracted to the `rubocop-capybara` gem.
(obsolete configuration found in config/default.yml, please update it)
Error: unrecognized cop or department FactoryBot/AssociationStyle found in config/default.yml
unrecognized cop or department FactoryBot/ConsistentParenthesesStyle found in config/default.yml
unrecognized cop or department FactoryBot/SyntaxMethods found in config/default.yml
```

And attempt to paste into ox.

**What behaviour were you expecting?**

I expect the paste to not strip new lines.

**Screenshots (if applicable)**

<img width="1205" alt="Screenshot 2024-12-20 at 15 29 01" src="https://github.com/user-attachments/assets/66311ae2-c3a9-4e8c-931a-adc293b706ea" />

**Comment by curlpipe** [comment]
Thank you for the bug report. I've been unable to reproduce this on my system.

May I ask the following questions, just so I can further investigate:

- What version of Ox are you using?
- What terminal emulator are you using?
- What operating system are you using?

I have the following theories
- **Terminal Emulator**
    - Duplicate key bindings for paste combination e.g. ctrl+v pastes and does something else?
    - Behaviour is different on your terminal emulator to the ones I've tested
    - Somehow it's ignoring bracketed paste, or messing with it?
- **Operating System**
    - macOS can be a bit strange when it comes to input because crossterm can report different things as input from Linux / Windows
- **Ox itself**
    - Some bug caused by the contents of the paste text (like different newline endings, or strange characters)
    - Some strange edge case where it breaks that hasn't been discovered yet

**Comment by pboling** [comment]
Answering the easy ones first:
```
❯ ox -v
0.7.4
```

I use iTerm2, and the (old, basic) RubyMine terminal, and I run `zsh`.  The behavior is the same in both.
```
❯ echo $TERM
xterm-256color
❯ zsh --version
zsh --version
zsh 5.9 (arm-apple-darwin22.1.0)
```

I also use oh-my-zsh, and powerline 10k, a zsh theme: https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#oh-my-zsh.

Note: The key bindings suggested by the ox runtime are often incorrect / confusing, as suggestions are usually uppercase, but only work when lower case.  (e.g. `ctrl+s`, not `ctrl+S`).

**Comment by curlpipe** [comment]
Thanks for your response, I'm pretty confident this is something to do with macOS input, I'll fire up my test machine and get debugging. Hopefully this can get patched ready for the next release!

**Comment by pboling** [comment]
Also, FWIW, I'm on the latest MacOS, Sequoia 15.2.

I have tried bouncing the copied text through a basic GUI text editor (like Smultron, or Text Edit), pasting it there, and recopying, just to be sure it isn't an artifact from the source of the copy.  It has not made any difference.

**Comment by kachick** [comment]
I can reproduce this problem in Windows Terminal.

- ox 0.7.5 runs in WSL2
- alacritty 0.14.0
- Windows Terminal 1.21.3231.0

Both terminals correctly cut multi-line text with Ctrl+x. I checked the clipboard history.
However, when pasting, Windows Terminal trims the line endings.

It occurs with every text. Both of LF/CRLF.
For example

```
a
b
```

to

```
ab
```

**Comment by curlpipe** [comment]
@kachick Thank you for the info. I think I have managed to reproduce this on my windows machine in windows terminal.

Interestingly, when I copy some text with newlines from an external editor (notepad++) , it pastes in perfectly. The only time it starts removing newlines is when I copy and paste within Ox itself.

Very strange behaviour. I'll look into this.

**Comment by curlpipe** [comment]
I think vim might interact with the system's clipboard directly whereas Ox just piggybacks on the terminal emulator feeding it the paste text. I originally added vim-style clipboard management, but it was removed because it was quite heavy and didn't work over SSH.

@pboling @kachick do you happen to get a warning message immediately after pasting text with newlines that says something like `ctrl+enter` not bound? I have a suspicion that the terminal emulator is somehow feeding in the paste text, treating newlines as a `ctrl+enter` key press, thus it is ignoring it because of that ctrl modifier.

**Comment by pboling** [comment]
I haven't seen that on Mac, no.

**Comment by curlpipe** [comment]
Ok, so I might have found the error.

Ox always enables something called bracketed paste, which helps speed up pasting and prevents weird behaviour.

Not all terminals support bracketed paste, but strangely, when a terminal doesn't support it, and it is enabled, it messes with pasted `\n` characters by making them show up as `ctrl+enter` instead of `enter`, Ox thinks "ctrl+enter" is a key binding, not a newline, so it doesn't insert it into the document.

Luckily, when I *don't* enable bracketed paste on terminals that don't support it, `\n` shows up as `enter`, which is exactly what it should show up as.

I'll open an issue in the `crossterm` crate (what Ox uses for terminal interaction) to see if they have any information as to whether this is a bug with crossterm, or just a weird quirk of terminals.

If that doesn't lead to anything I might be able to work out a way to intelligently switch it off if it detects it isn't working, thus restoring normal paste behaviour on systems where bracketed paste is not supported.

**Comment by curlpipe** [comment]
On further research, I found some existing issues that are related to this:


This one indicates that some terminals send `\r` instead of `\n`:
https://github.com/crossterm-rs/crossterm/issues/780

This one hints at the issue I discovered in my previous comment:
https://github.com/crossterm-rs/crossterm/issues/737

So there might be 2 different issues at play here. Very interesting.

So I will implement 2 fixes:
- I will simply replace all `\r` with `\n` in the paste handler
- On windows, I will disable bracketed paste

hopefully these work?

**Comment by curlpipe** [comment]
Issue opened here https://github.com/crossterm-rs/crossterm/issues/962

**Comment by pboling** [comment]
Looking forward to testing it out!

**Comment by curlpipe** [comment]
These changes should be published with 0.7.6

Let me know if they work!

I'll keep this issue open until everything works 100% 👍

**Comment by kachick** [comment]
Thank you for the ⚡ quick fix!
It looks like working with Windows Terminal, alacritty and kitty 🎉

**Comment by pboling** [comment]
Not available in homebrew yet, but will try it when it is!

**Comment by curlpipe** [comment]
Fantastic news! :tada: Thank you to you both for your help.

Happy editing!
