### ISSUE TITLE
Windows OS Support

### ISSUE THREAD

**Issue by cdegalitt** [curlpipe/ox#34]
Hi,

I was really eager to try ox but wasn't able to compile it on my system.
It seems to be due to its dependency towards termion, which lacks for Windows support ([as stated here](https://gitlab.redox-os.org/redox-os/termion/-/issues/103)). You can see my error log below :

error[E0433]: failed to resolve: unresolved import
  --> C:\Users\cdeliquaire\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.5\src\lib.rs:24:9
   |
24 | pub use sys::size::terminal_size;
   |         ^^^
   |         |
   |         unresolved import
   |         help: a similar path exists: `color::env::sys`

Do you plan to support Windows OS someday ?
If so, It seems that some people/projects successfuly switched to [crossterm](https://github.com/crossterm-rs/crossterm) instead of termion to gain true multi-platform terminal support, I don't know if it supports the whole feature set ox requires, but this could be a lead.

Thanks by advance.

**Comment by curlpipe** [comment]
Hello! I have looked into this and moving to crossterm is already on the list of things to do. There are a few things I wish to add beforehand but Windows support is definitely a priority for me because Termion isn't a very advanced library and is a huge limiting factor in terms of platform support, keybindings and efficiency overall. Hopefully I'll get Ox working on Windows within the next month or maybe even less if things go to plan (which they are as of now).

Thank you for your interest :smile:

**Comment by ChayimFriedman2** [comment]
WSL?

**Comment by FuSoftware** [comment]
> 
> 
> WSL?

Windows Subsystem for Linux, a feature allowing you install a Linux subsystem inside Windows that you can access through PowerShell

**Comment by ChayimFriedman2** [comment]
> > WSL?
> 
> Windows Subsystem for Linux, a feature allowing you install a Linux subsystem inside Windows that you can access through PowerShell

I know what's WSL 🤣 🤣 🤣. I meant until there is an official Windows build, you can use WSL.

**Comment by ChayimFriedman2** [comment]
And PowerShell does not belong here.

**Comment by curlpipe** [comment]
I'll be working on this in the next week I'll keep you guys posted on how the migration to `Crossterm` is going. Hopefully everything goes to plan. 🤞 👍

**Comment by curlpipe** [comment]
I've worked on it a bit and I have managed to completely replace `termion` with `crossterm`. Crossterm is a much better library and the code layout is a lot more clear. I haven't checked to see if it compiles on Windows just yet but I will be checking it soon and hopefully it works. There might be an issue with the colour scheme on cmd.exe due to the lack of 24bit true colours, many macOS users who are using the default terminal experience weird colour issues where the editor turns red because of the colour depth but I'll be adding a 16 bit colour fallback option with 0.2.7.

**Comment by ChayimFriedman2** [comment]
Windows users can use the new Windows Terminal that does have true colors

**Comment by cdegalitt** [comment]
Thank you @curlpipe ! 

ox built successfuly on my Windows 10 machine (version 10.0.19041.508)

Although i do miss some fonts for it to render properly some utf-8 "icons", it runs, looks and feels nice and smooth under Windows Terminal within cmd.exe shell :)

Alternative TTYs such as Git Bash's MinGW64 does not seem to appreciate it, but that's another story...

I hope to have some time in the near future to look at those issues and maybe contribute. I've been wanting to learn Rust development since a year now !

Cheers!

**Comment by cdegalitt** [comment]
> And PowerShell does not belong here.

who uses it anyway ? 🤣

**Comment by ChayimFriedman2** [comment]
> > And PowerShell does not belong here.
> 
> who uses it anyway ? 🤣

I 😄

**Comment by curlpipe** [comment]
@cdegalitt Great! You can change the status line and tab line format using the configuration file to remove or replace those unicode icons. You can see them in the new wiki which tells you how to change them.
