### ISSUE TITLE
Parse Error - ExpectedStruct

### ISSUE THREAD

**Issue by jashsayani** [curlpipe/ox#41]
**Describe the bug**
Parse Error when you open a new blank file.

**To Reproduce**
1. Go to `~/.config/ox/`
2. Run `touch ox.ron`
3. Run `ox ox.ron`

**Screenshots**
![Screen Shot 2020-11-02 at 11 37 52 PM](https://user-images.githubusercontent.com/18684/97959730-d3116600-1d64-11eb-80bf-8113b0d252a2.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux (custom distro)

**Comment by curlpipe** [comment]
What version are you using?

**Comment by curlpipe** [comment]
This is probably because you have made your configuration file blank (and that error is just saying that you have an invalid format of configuration file). You can hide this error by copying the example configuration file from https://github.com/curlpipe/ox/blob/master/config/ox.ron and putting it where `~/.config/ox/ox.ron` is, you can also change this configuration file to customize and change the way Ox works. :)

**Comment by jashsayani** [comment]
Yes, I know its showing the error because its a blank file (just touched it). But why should a text editor try parsing my file? If its for syntax highlighting, it should fail silently rather than showing an error in red.

**Comment by curlpipe** [comment]
Because it exists, therefore it thinks that you've got configuration information in it and tries to parse it. Perhaps I could add a check to see if the file is empty :)

**Comment by curlpipe** [comment]
Added an information message for empty configuration files for 0.2.7.
![image](https://user-images.githubusercontent.com/11898833/98597463-fdb56e80-22d0-11eb-9ad1-c65706c38935.png)
