### ISSUE TITLE
PHP syntax highlighting

### ISSUE THREAD

**Issue by duboiss** [curlpipe/ox#60]
**Is your feature request related to a problem? Please describe.**
It would be nice if we can add a support for PHP syntax highlighting.
I also think there are some similarities with the current JavaScript support (comments, functions...).

Why not have an issue where people can request support for a particular file extension and then they can vote ? To add support to the most requested in priority.

Thanks!

**Comment by curlpipe** [comment]
Sure, shouldn't be too hard. I am writing some documentation at the moment to educate how to configure and create custom syntax highlighting but I'm more than happy to create PHP syntax highlighting if I get the time. 

As for the idea where people can request support for a particular file extension, I could open one issue and pin it where people can comment for certain file types however there aren't enough language requests and I'll probably add language support using a list of popular programming languages and just work my way down to cover most of the popular languages and then perhaps the more obscure ones can open individual issues.

**Comment by DuboisS** [comment]
You are awesome.
I'm not a Rust developer but I have found the ox.ron where syntax highlighting is handled. After see it, I think I havent the knowledge for PR... so sorry about that.

I talked about the new issue because some file extensions do not correspond to a language. `.env` is an exemple.

Thanks you for your work!

**Comment by curlpipe** [comment]
Well, I realise this issue was made ages ago, but I recently rewrote Ox, and PHP syntax highlighting is included.
Apologies that it took 4 years to get here, but I really wanted to focus on rebuilding it as the older versions got quite messy and unreliable. The versions 0.3.0 and up are looking to be a lot more reliable.
